"""Run image predictions with the exported Teachable Machine mammal model.

Example (from this folder):
    py -3.10 predict.py "C:\\path\\to\\animal.jpg"
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps, UnidentifiedImageError


PROJECT_DIR = Path(__file__).resolve().parent
DEFAULT_MODEL_PATH = PROJECT_DIR / "converted_keras" / "keras_model.h5"
DEFAULT_LABELS_PATH = PROJECT_DIR / "converted_keras" / "labels.txt"


def positive_integer(value: str) -> int:
    """Argparse validator for values such as --top-k."""
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return number


def load_labels(labels_path: Path, expected_count: int) -> list[str]:
    """Read Teachable Machine labels, removing its leading class numbers."""
    lines = [line.strip() for line in labels_path.read_text(encoding="utf-8").splitlines()]
    lines = [line for line in lines if line]

    if not lines:
        raise ValueError(f"No labels were found in: {labels_path}")

    numbered_labels: dict[int, str] = {}
    unnumbered_labels: list[str] = []
    for line in lines:
        match = re.match(r"^(\d+)\s+(.+)$", line)
        if match:
            numbered_labels[int(match.group(1))] = match.group(2).strip()
        else:
            unnumbered_labels.append(line)

    if numbered_labels and not unnumbered_labels:
        labels = [numbered_labels.get(index, "") for index in range(expected_count)]
        if any(not label for label in labels) or len(numbered_labels) != expected_count:
            raise ValueError(
                f"The labels file has {len(numbered_labels)} numbered labels, but the model "
                f"has {expected_count} output classes."
            )
        return labels

    if len(lines) != expected_count:
        raise ValueError(
            f"The labels file has {len(lines)} labels, but the model has "
            f"{expected_count} output classes."
        )
    return lines


def model_image_size(model) -> tuple[int, int]:
    """Return the (width, height) required by a single RGB image input."""
    input_shape = model.input_shape
    if isinstance(input_shape, list):
        raise ValueError("This script supports a model with one image input only.")
    if len(input_shape) != 4:
        raise ValueError(f"Expected an image input of shape (batch, height, width, channels), got {input_shape}.")

    _, height, width, channels = input_shape
    if not isinstance(height, int) or not isinstance(width, int) or channels != 3:
        raise ValueError(f"Expected a fixed RGB image input, got {input_shape}.")
    return width, height


def model_class_count(model) -> int:
    """Return the number of classification outputs for a single-output model."""
    output_shape = model.output_shape
    if isinstance(output_shape, list) or len(output_shape) != 2 or not isinstance(output_shape[-1], int):
        raise ValueError(f"Expected one classification output, got {output_shape}.")
    return output_shape[-1]


def prepare_image(image_path: Path, size: tuple[int, int]) -> np.ndarray:
    """Apply Teachable Machine's RGB, center-crop, resize, and [-1, 1] normalization."""
    with Image.open(image_path) as opened_image:
        image = ImageOps.exif_transpose(opened_image).convert("RGB")

    # This is the same preprocessing used by the Keras code generated by
    # Teachable Machine: resize to cover the target size, then center-crop.
    resampling = Image.Resampling.LANCZOS if hasattr(Image, "Resampling") else Image.LANCZOS
    image = ImageOps.fit(image, size, method=resampling)
    image_array = np.asarray(image, dtype=np.float32)
    normalized = (image_array / 127.5) - 1.0
    return np.expand_dims(normalized, axis=0)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Classify one image with the exported Teachable Machine mammal model."
    )
    parser.add_argument(
        "image",
        type=Path,
        nargs="?",
        help="Path to a JPG, PNG, or other Pillow-supported image. If omitted, you will be prompted.",
    )
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL_PATH, help="Path to a Keras .h5 model.")
    parser.add_argument("--labels", type=Path, default=DEFAULT_LABELS_PATH, help="Path to the labels.txt file.")
    parser.add_argument("--top-k", type=positive_integer, default=3, help="Number of highest-confidence classes to print.")
    return parser.parse_args()


def main() -> int:
    args = parse_arguments()

    if args.image is None:
        try:
            entered_path = input("Enter the full path to an animal image: ").strip().strip('"')
        except (EOFError, KeyboardInterrupt):
            print("\nError: No image path was provided.", file=sys.stderr)
            return 2

        if not entered_path:
            print("Error: No image path was provided.", file=sys.stderr)
            return 2
        args.image = Path(entered_path)

    for path, description in ((args.image, "Image"), (args.model, "Model"), (args.labels, "Labels file")):
        if not path.is_file():
            print(f"Error: {description} was not found: {path}", file=sys.stderr)
            return 2

    try:
        # Set this before TensorFlow is imported so ordinary predictions are not
        # buried under its informational CPU-startup messages.
        os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
        logging.getLogger("tensorflow").setLevel(logging.ERROR)
        import tensorflow as tf

        tf.get_logger().setLevel("ERROR")
        model = tf.keras.models.load_model(args.model, compile=False)
        class_count = model_class_count(model)
        labels = load_labels(args.labels, class_count)
        image_batch = prepare_image(args.image, model_image_size(model))
        probabilities = np.asarray(model.predict(image_batch, verbose=0))[0]

        if probabilities.size != class_count:
            raise ValueError(
                f"The model returned {probabilities.size} values, expected {class_count}."
            )

    except ModuleNotFoundError as error:
        if error.name == "tensorflow":
            print(
                "Error: TensorFlow is not installed. Run: py -3.10 -m pip install -r requirements.txt",
                file=sys.stderr,
            )
            return 1
        raise
    except (OSError, ValueError, UnidentifiedImageError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    best_index = int(np.argmax(probabilities))
    print(f"Prediction: {labels[best_index]}")
    print(f"Confidence: {probabilities[best_index] * 100:.2f}%")
    print(f"\nTop {min(args.top_k, class_count)} results:")
    for rank, index in enumerate(np.argsort(probabilities)[::-1][: args.top_k], start=1):
        print(f"{rank}. {labels[int(index)]}: {probabilities[int(index)] * 100:.2f}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
